# Generated by Django 5.0 on 2024-10-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_name', models.CharField(max_length=50)),
                ('prod_year', models.DateField()),
                ('zhanr', models.CharField(max_length=60)),
                ('aftor', models.CharField(max_length=60)),
            ],
        ),
    ]
