# Generated by Django 5.0 on 2024-10-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_student_narkhi_kitob_student_suporidansh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='suporidansh',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
