# Generated by Django 5.0 on 2024-10-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_biliotekahi_biblateka_alter_books_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rohbar',
            name='rohbar',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.student')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.city')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.region')),
            ],
        ),
        migrations.DeleteModel(
            name='Biliotekahi',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.DeleteModel(
            name='Rohbar',
        ),
    ]
